task :default => :lexer_test

task :lexer_test do
  d = "zenspider/10"

  %w[
     ArrayTest/Main.jack
     ExpressionlessSquare/Main.jack
     ExpressionlessSquare/SquareGame.jack
     ExpressionlessSquare/Square.jack
     Square/Main.jack
     Square/SquareGame.jack
     Square/Square.jack
  ].each do |input|
    expected = input.sub(/\.jack$/, "T.xml")
    sh "racket jack-lexer.rkt #{input} | ./normalize.rb > wtf.xml"
    sh "cd ..; rake diff F='#{d}/wtf.xml' F2='#{d}/#{expected}'"
  end

  rm_f "wtf.xml"
end
