emulator = File.expand_path File.join "..", "..", "tools", "CPUEmulator.sh"
my_vm = "ruby vm.rb"

def tool t, f=nil
  file = f ? File.expand_path(File.join(File.dirname(__FILE__), f)) : ""
  `#{t + " " + file}`
end

def filename(f) f + "/" + f.split("/").last end
def asm(f)  filename(f) + ".asm" end
def tst(f)  filename(f) + ".tst" end
def out(f)  filename(f) + ".out" end
def _cmp(f) filename(f) + ".cmp" end

tests = %w[
  ProgramFlow/BasicLoop
  ProgramFlow/FibonacciSeries
  FunctionCalls/SimpleFunction
  FunctionCalls/FibonacciElement
  FunctionCalls/StaticsTest
]

tests.each do |t|
  task t do
    sh "#{my_vm} #{t} > #{asm(t)}"
    tool emulator, tst(t)

    unless $?.success?
      abort ["Expected:", File.read(_cmp(t)), "Got:", File.read(out(t))].join("\n")
    end
  end
end

task :default => :test

task :test => [:clean_out, *tests]

task :clean => [:clean_out, :clean_asm]

task :clean_out do
  tests.each {|t| rm out(t) rescue nil }
end

task :clean_asm do
  tests.each {|t| rm asm(t) rescue nil }
end
