emulator = File.expand_path File.join "..", "..", "tools", "CPUEmulator.sh"
my_vm = "ruby vm.rb"

def tool t, f=nil
  file = f ? File.expand_path(File.join(File.dirname(__FILE__), f)) : ""
  `#{t + " " + file}`
end

def filename(f) f + "/" + f.split("/").last end
def asm(f)  filename(f) + ".asm" end
def tst(f)  filename(f) + ".tst" end

tests = %w[
  ProgramFlow/BasicLoop
  ProgramFlow/FibonacciSeries
  FunctionCalls/SimpleFunction
  FunctionCalls/FibonacciElement
]

tests.each do |t|
  task t do
    sh "#{my_vm} #{t} > #{asm(t)}"
    tool emulator, tst(t)

    unless $?.success?
      outfile = filename(t) + ".out"
      cmp = filename(t) + ".cmp"

      abort ["Expected:", File.read(cmp), "Got:", File.read(outfile)].join("\n")
    end
  end
end

task :default => :test

task :test => [:clean, *tests]

task :clean do
  tests.each {|t| rm asm(t) rescue nil }
end
