task :default => :test

rule ".vm" => ".jack" do |t|
  base = t.source.sub(/\.jack$/, "")
  full = File.expand_path base
  sh "../../tools/JackCompiler.sh #{full}.jack"
end

def wire base
  file "#{base}.vm" => [ "Rakefile", "#{base}.jack"]

  task :extra => "#{base}.vm" do
    sh %[./jack.rkt #{base}.jack > wtf.vm && diff -bu #{base}.vm wtf.vm]
  end
end

task :test do
  d = "zenspider/11"

  files = []

  files << "Main"
  files << "MathX"
  files << "Grid"
  files << "Pew"
  files << "Trig"
  files << "Ship"

  files.each do |name|
    sh %[./jack.rkt ../09/grid/#{name}.jack > wtf.vm]
    sh "diff -bu ../09/grid/#{name}.vm wtf.vm"
  end

  rm_f Dir["wtf.vm"]
end

%w[ Average/Main ComplexArrays/Main ConvertToBin/Main Pong/Ball Pong/Bat
    Pong/Main Pong/PongGame Seven/Main Square/Main Square/Square
    Square/SquareGame ].each do |f|
  wire f
end
