file "vm1.rb"

rule ".asm" => ".vm" do |t|
  sh "./vm1.rb #{t.source} > #{t.name}"
end

rule ".out" => ".asm" do |t|
  base = t.source.sub(/\.asm$/, "")
  full = File.expand_path base
  sh "../../tools/CPUEmulator.sh #{full}.tst || diff -u #{base}.cmp #{t.name}"
end

def wire base
  file "#{base}.asm" => [ "Rakefile", "vm1.rb", "#{base}.vm"]
  file "#{base}.out" => [ "#{base}.asm" ]
  task :default => "#{base}.out"
end

wire "StackArithmetic/SimpleAdd/SimpleAdd"
wire "StackArithmetic/StackTest/StackTest"
wire "MemoryAccess/BasicTest/BasicTest"
